#!/bin/sh

set -eu

status () {
  echo "---> ${@}" >&2
}

# set WAN performance optimizations and segment support
WSREP_PROVIDER_OPTIONS=""

set +u

if [ ! -z ${SEGMENT} ]; then
    if [ "$SEGMENT" -eq "$SEGMENT" > /dev/null 2>&1 ]; then
        WSREP_PROVIDER_OPTIONS="gmcast.segment = $SEGMENT; "
    else 
            echo "SEGMENT must be an integer"
            exit 1
    fi
fi

if [ ! -z ${WAN} ]; then
    WSREP_PROVIDER_OPTIONS=$WSREP_PROVIDER_OPTIONS"gcache.size = 2G; gcs.fc_limit = 128; evs.send_window = 1024; \
      evs.user_send_window = 512; evs.keepalive_period = PT3S; evs.inactive_check_period = PT10S; \
      evs.suspect_timeout = PT30S; evs.inactive_timeout = PT1M;"
fi

set -u

echo $WSREP_PROVIDER_OPTIONS
exit 0
if [ -z ${CLUSTER+x} ]; then
    echo "CLUSTER variable must be BOOT, INIT or cluster node list"
    exit 1
elif [ ${CLUSTER} = "BOOT" ]; then
    ln -sf /etc/mysql/my-init.cnf /etc/mysql/my.cnf
else
    ln -sf /etc/mysql/my-cluster.cnf /etc/mysql/my.cnf
fi

mv /usr/bin/xtrabackup /usr/bin/xtrabackup_51
ln -sf /usr/bin/xtrabackup_55 /usr/bin/xtrabackup

if [ -d /etc/ssl/mysql ]; then
   chown mysql:mysql /etc/ssl/mysql/*.pem
fi

# create link for less flexible scripts

ln -sf /var/lib/mysql/mysql.sock /var/run/mysqld/mysqld.sock

if [ -z ${CLUSTER+x} ]; then
    echo "CLUSTER variable must be BOOT, INIT or cluster node list"
    exit 1
elif [ ${CLUSTER} = "BOOT" ]; then
    if [ ! -e /var/lib/mysql/bootstrapped ]; then
        status "Bootstrapping MariaDB installation..."

        status "Initializing MariaDB root directory at /var/lib/mysql"
        mysql_install_db

        status "Setting MariaDB root password"
        /usr/bin/mariadb-setrootpassword
        touch /var/lib/mysql/bootstrapped
    else
        status "Starting from already-bootstrapped MariaDB installation"
    fi

    exec /usr/bin/mysqld_safe --log-error=/var/lib/mysql/mysql.error.log
elif [ ${CLUSTER} = "INIT" ]; then
    NODE=1 # force this
    # grab the ip address of eth0 if NODE_ADDR is not provided 
    NODE_ADDR=${NODE_ADDR:-$(ip -4 addr show eth0 | grep inet | sed -e 's/  */ /g' | cut -d ' ' -f 3 | cut -d '/' -f 1)}
    exec /usr/bin/mysqld_safe --wsrep_node_address="${NODE_ADDR}" \
        --wsrep_node_incoming_address="${NODE_ADDR}" \
        --wsrep_new_cluster --wsrep_cluster_address="gcomm://" \
        --wsrep_provider_options="$WSREP_PROVIDER_OPTIONS" \
        --log-error=/var/lib/mysql/mysql-$NODE.error.log
else
    if [ -z ${NODE+x} ]; then
        echo "Must define node number" >&2
        exit 1
    fi
    NODE_ADDR=${NODE_ADDR:-$(ip -4 addr show eth0 | grep inet | sed -e 's/  */ /g' | cut -d ' ' -f 3 | cut -d '/' -f 1)}
    CLUSTER="gcomm://$CLUSTER"
    exec /usr/bin/mysqld_safe --wsrep_node_address="${NODE_ADDR}" \
        --wsrep_node_incoming_address="${NODE_ADDR}" \
        --wsrep_provider_options="$WSREP_PROVIDER_OPTIONS" \
        --wsrep_cluster_address=$CLUSTER --log-error=/var/lib/mysql/mysql-$NODE.error.log
fi

