#!/usr/bin/env lua

-- check mysql wsrep by "show status like 'wsrep_%'"
-- author: nsasikumar@connectify.me

require("plugin")

-- do check
function check(opts) 
  luasql = require "luasql.mysql"
  env = assert (luasql.mysql())
  con = assert (env:connect("mysql", opts["username"], opts["password"], opts["host"], tonumber(opts["port"])))
  -- retrive wsrep variables
  cur = assert (con:execute"show global variables like 'wsrep_%'")
  row = cur:fetch ({}, "a")
  while row do
    name = string.sub(row.Variable_name, string.len('wsrep_') + 1)
    print(string.format("entry:variable:%s: %s", name, row.Value))
    row = cur:fetch (row, "a")
  end
  -- retrieve wsrep status
  cur = assert (con:execute"show global status like 'wsrep_%'")
  row = cur:fetch ({}, "a")
  while row do
    metric = string.sub(row.Variable_name, string.len('wsrep_') + 1)
    print(string.format("metric:%s: %s", metric, row.Value))
    row = cur:fetch (row, "a")
  end
  -- close everything
  cur:close()
  con:close()
  env:close()
end

-- usage
function usage() 
  print("usage: check_mysql_wsrep --host=Host --username=User --password=Password --port=Port")
end

-- parse arguments
opts = getopt(arg, {"host", "password", "username", "port"})
if not opts["port"] then opts["port"] = "3306" end
for i, o in ipairs({"host", "password", "username"}) do
  if not opts[o] then
    print(string.format("UNKNOWN - miss argument = '%s'\n", o))
    usage()
    return
  end
end

status, err = pcall(check, opts) 
if not status then
  print("UNKNOWN - plugin internal error\n")
  print(err)
end
