#!/usr/bin/env lua

-- check mysql wsrep by "show status like 'wsrep_%'"
-- author: nsasikumar@connectify.me

require("plugin")

-- do check
function check(opts) 
  luasql = require "luasql.mysql"

  allValues = {}

  env = assert (luasql.mysql())
  con = assert (env:connect("mysql", opts["username"], opts["password"], opts["host"], tonumber(opts["port"])))
  -- retrive wsrep variables
  cur = assert (con:execute"show global variables like 'wsrep_%'")
  row = cur:fetch ({}, "a")
  while row do
    name = string.sub(row.Variable_name, string.len('wsrep_') + 1)
    print(string.format("entry:variable:%s: %s", name, row.Value))
    allValues[name] = row.Value
    row = cur:fetch (row, "a")
  end
  -- retrieve wsrep status
  cur = assert (con:execute"show global status like 'wsrep_%'")
  row = cur:fetch ({}, "a")
  while row do
    metric = string.sub(row.Variable_name, string.len('wsrep_') + 1)
    print(string.format("metric:%s: %s", metric, row.Value))
    allValues[metric] = row.Value
    row = cur:fetch (row, "a")
  end
  -- close everything
  cur:close()
  con:close()
  env:close()

  if allValues["cluster_size"] <= "0" or allValues["cluster_status"] ~= "Primary" or allValues["connected"] ~= "ON" or allValues["ready"] ~= "ON" then
    error("WSREP values do not match.")
    os.exit(1)
  end

return allValues

end

-- usage
function usage() 
  print("usage: check_mysql_wsrep --host=Host --username=User --password=Password --port=Port")
end

-- parse arguments
opts = getopt(arg, {"host", "password", "username", "port"})
if not opts["port"] then opts["port"] = "3306" end
for i, o in ipairs({"host", "password", "username"}) do
  if not opts[o] then
    print(string.format("UNKNOWN - miss argument = '%s'\n", o))
    usage()
    os.exit(1)
  end
end

status, err = pcall(check, opts) 
if not status then
  print("UNKNOWN - plugin internal error\n")
  print(err)
  os.exit(1)
end
